language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t romanbeloborodov/rombelrepo:tests -f ./client/Dockerfile.dev ./client

script:
  - docker run romanbeloborodov/rombelrepo:tests npm run test -- --coverage

after_success:
 - docker build -t romanbeloborodov/rombelrepo:multi-client ./client
 - docker build -t romanbeloborodov/rombelrepo:multi-nginx ./nginx
 - docker build -t romanbeloborodov/rombelrepo:multi-server ./server
 - docker build -t romanbeloborodov/rombelrepo:multi-worker ./worker
  #Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push romanbeloborodov/rombelrepo:multi-client
 - docker push romanbeloborodov/rombelrepo:multi-nginx
 - docker push romanbeloborodov/rombelrepo:multi-server
 - docker push romanbeloborodov/rombelrepo:multi-worker

 deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-458718470893
  bucket_path: multidocker
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

