language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t tests -f ./client/Dockerfile.dev ./client

script:
  - docker run tests npm run test -- --coverage

after_success:
 - docker build -t multi-client ./client
 - docker build -t multi-nginx ./nginx
 - docker build -t multi-server ./server
 - docker build -t multi-worker ./worker
  #Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push multi-client/"$DOCKERHUB_REPO_NAME"
 - docker push multi-nginx/"$DOCKERHUB_REPO_NAME"
 - docker push multi-server/"$DOCKERHUB_REPO_NAME"
 - docker push multi-worker/"$DOCKERHUB_REPO_NAME"

